<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Admin Landing Page</title>
</head>
<body>
<%
    if ((session.getAttribute("user") == null)) {
%>
You are not logged in<br/>
<a href="ALogin.jsp">Please Login</a>
<%} else {
%>
 Welcome <%=session.getAttribute("user") %>
 <br>***ONLY PICK ONE OPTION AT A TIME***<br>
<p style="float: right;"><a href="ALogout.jsp">Log out</a></p>
<br>

<form action="AFlightLog.jsp" method="POST">
	Retrieve list of all flights for an airport:
	<br><input type="text" name="airport_id" placeholder="Enter Airport">

	<form action="AFlightLog.jsp">
		<input type="submit" value="Retrieve">
	</form>
</form>

<form action="ASalesReport.jsp" method="POST">
	Sales report for all tickets with PURCHASE DATE in the month of:
	<br>**month format is 01=January, 12=December
	<br><input type="text" name="month" placeholder="Enter Month">

	<form action="ASalesReport.jsp">
		<input type="submit" value="Retrieve">
	</form>
</form>

<form action="AFlightReservations.jsp" method="POST">
	Retrieve list of all reservations by flight number:
	<br><input type="text" name="airline_id" placeholder="Enter Airline ID"> <br>
	<input type="text" name="aircraft_id" placeholder="Enter Aircraft ID">

	<form action="AFlightReservations.jsp">
		<input type="submit" value="Retrieve">
	</form>
</form>

<form action="AReservByCust.jsp" method="POST">
	Retrieve list of all reservations by customer name:
	<br><input type="text" name="customerID" placeholder="Enter Customer ID"> <br>


	<form action="AReservByCust.jsp">
		<input type="submit" value="Retrieve">
	</form>
</form>


<form action="ARevByFlight.jsp" method="POST">
	Revenue generated by flight:
	<br><input type="text" name="airline_id" placeholder="Enter Airline ID"><br>
	<input type="text" name="aircraft_id" placeholder="Enter Aircraft ID">

	<form action="ARevByFlight.jsp">
		<input type="submit" value="Retrieve">
	</form>
</form>

<form action="ARevByAirline.jsp" method="POST">
	Revenue generated by airline:
	<br><input type="text" name="airline_id" placeholder="Enter Airline ID">


	<form action="ARevByAirline.jsp">
		<input type="submit" value="Retrieve">
	</form>
</form>

<form action="ARevByCustomer.jsp" method="POST">
	Revenue generated by customer:
	<br><input type="text" name="userid" placeholder="Enter Customer Username">

	<form action="ARevByCustomer.jsp">
		<input type="submit" value="Retrieve">
	</form>
</form>

	<form action="AMostActFlights.jsp">
		<input type="submit" value="Retrieve">
	</form>
</form>

<form action="AMostRevByCustomer.jsp" method="POST">
	Most revenue generated by customer:
	<br><input type="text" name="userid" placeholder="Enter Customer Username">

	<form action="ARevByCustomer.jsp">
		<input type="submit" value="Retrieve">
	</form>
</form>


<%
    }
%>
</body>
</html>